const data = [
    {
        id: 1,
        title: "Home Assistant trên Raspberry Pi: cài nhanh, gọn, đẹp",
        excerpt: "Hướng dẫn rút gọn để biến Raspberry Pi thành trung tâm nhà thông minh, dễ làm và ổn định.",
        img: "img.png",
        category: "Raspberry Pi",
        author: "author.jpg",
        authorname: "Lưu Nhân",
        date: "24 Tháng 2 2026",
        duration: "10",
        tags: ["Home Assistant", "Smart Home"],
    },
    {
        id: 2,
        title: "Raspberry Pi OS: cài đặt chuẩn cho người mới bắt đầu",
        excerpt: "Từng bước cài hệ điều hành Raspberry Pi OS, tối ưu hiệu năng và bảo mật cơ bản.",
        img: "img2.png",
        category: "Raspberry Pi",
        author: "author.jpg",
        authorname: "Ngọc Lan",
        date: "20 Tháng 2 2026",
        duration: "8",
        tags: ["Raspberry Pi", "OS"],
    },
    {
        id: 3,
        title: "Biến Raspberry Pi thành server mini cho gia đình",
        excerpt: "Tạo server lưu trữ nhẹ, truy cập mọi nơi, tiết kiệm và dễ mở rộng.",
        img: "img3.png",
        category: "Raspberry Pi",
        author: "author.jpg",
        authorname: "Tuấn Kiệt",
        date: "18 Tháng 2 2026",
        duration: "12",
        tags: ["Server", "Self-host"],
    },
    {
        id: 4,
        title: "Những sự thật kinh doanh giúp bạn thành công",
        excerpt: "Trang bị kiến thức và chiến lược đã được kiểm chứng để bứt phá sự nghiệp.",
        img: "img4.png",
        category: "Kinh doanh",
        author: "author.jpg",
        authorname: "Harry",
        date: "27 Tháng 6 2026",
        duration: "89",
        tags: ["Du lịch", "Phong cách sống"],
    },
    {
        id: 5,
        title: "60 việc cần làm để xây dựng kế hoạch",
        excerpt: "Khám phá cách lập kế hoạch và tư duy chiến lược để đạt mục tiêu hiệu quả.",
        img: "img5.png",
        category: "Xây dựng",
        author: "author.jpg",
        authorname: "Roney",
        date: "28 Tháng 6 2026",
        duration: "35",
        tags: ["Du lịch", "Phong cách sống"],
    },
    {
        id: 6,
        title: "Sống gần thiên nhiên với 7 mẹo đơn giản",
        excerpt: "Kết nối với thiên nhiên và trân trọng vẻ đẹp tự nhiên qua các gợi ý này.",
        img: "img6.png",
        category: "Kinh doanh",
        author: "author.jpg",
        authorname: "Haland",
        date: "25 Tháng 4 2026",
        duration: "15",
        tags: ["Du lịch", "Phong cách sống"],
    },
    {
        id: 7,
        title: "Đã đến lúc làm mới nguồn năng lượng của bạn",
        excerpt: "Hành trình phát triển bản thân giúp bạn thích nghi và mạnh mẽ hơn trước những đổi thay.",
        img: "img7.png",
        category: "Công nghệ",
        author: "author.jpg",
        authorname: "Elither",
        date: "25 Tháng 4 2026",
        duration: "14",
        tags: ["Du lịch", "Phong cách sống"],
    },
    {
        id: 8,
        title: "Tìm sự bình an trong chính mình",
        excerpt: "Thực hành chánh niệm để nuôi dưỡng bình an và cân bằng mỗi ngày.",
        img: "img8.png",
        category: "Thể thao",
        author: "author.jpg",
        authorname: "Etains",
        date: "25 Tháng 7 2026",
        duration: "22",
        tags: ["Du lịch", "Phong cách sống"],
    },
    {
        id: 9,
        title: "Khơi dậy sáng tạo với cảm hứng mới",
        excerpt: "Khơi mở khả năng sáng tạo để thể hiện bản thân và khám phá tiềm năng.",
        img: "img9.png",
        category: "Sự kiện",
        author: "author.jpg",
        authorname: "Lufffi",
        date: "28 Tháng 8 2026",
        duration: "18",
        tags: ["Du lịch", "Phong cách sống"],
    },
];
export default data;
