const categories = [
    {
        id: 1,
        title: "Du lịch",
        des: "Nội dung chọn lọc và cảm hứng dành cho bạn.",
        img: "tag1.png",
        imgBig: "cat1.png",
        postCount: "36",
        url: "Du lịch",
    },
    {
        id: 2,
        title: "Văn hóa",
        des: "Nội dung chọn lọc và cảm hứng dành cho bạn.",
        img: "tag2.png",
        imgBig: "cat2.png",
        postCount: "18",
        url: "",
    },
    {
        id: 3,
        title: "Phong cách sống",
        des: "Nội dung chọn lọc và cảm hứng dành cho bạn.",
        img: "tag3.png",
        imgBig: "cat3.png",
        postCount: "44",
        url: "",
    },
    {
        id: 4,
        title: "Thời trang",
        des: "Nội dung chọn lọc và cảm hứng dành cho bạn.",
        img: "tag4.png",
        imgBig: "cat4.png",
        postCount: "65",
        url: "",
    },
    {
        id: 5,
        title: "Ẩm thực",
        des: "Nội dung chọn lọc và cảm hứng dành cho bạn.",
        img: "tag5.png",
        imgBig: "cat5.png",
        postCount: "37",
        url: "",
    },
    {
        id: 6,
        title: "Vũ trụ",
        des: "Nội dung chọn lọc và cảm hứng dành cho bạn.",
        img: "tag6.png",
        imgBig: "cat6.png",
        postCount: "27",
        url: "",
    },
    {
        id: 7,
        title: "Động vật",
        des: "Nội dung chọn lọc và cảm hứng dành cho bạn.",
        img: "tag7.png",
        imgBig: "cat7.png",
        postCount: "16",
        url: "",
    },
    {
        id: 8,
        title: "Tối giản",
        des: "Nội dung chọn lọc và cảm hứng dành cho bạn.",
        img: "tag8.png",
        imgBig: "cat8.png",
        postCount: "87",
        url: "",
    },
    {
        id: 9,
        title: "Nội thất",
        des: "Nội dung chọn lọc và cảm hứng dành cho bạn.",
        img: "tag9.png",
        imgBig: "cat9.png",
        postCount: "27",
        url: "",
    },
    {
        id: 10,
        title: "Cây xanh",
        des: "Nội dung chọn lọc và cảm hứng dành cho bạn.",
        img: "tag10.png",
        imgBig: "cat10.png",
        postCount: "25",
        url: "",
    },
    {
        id: 11,
        title: "Thiên nhiên",
        des: "Nội dung chọn lọc và cảm hứng dành cho bạn.",
        img: "tag11.png",
        imgBig: "cat11.png",
        postCount: "43",
        url: "",
    },
    {
        id: 12,
        title: "Kinh doanh",
        des: "Nội dung chọn lọc và cảm hứng dành cho bạn.",
        img: "tag12.png",
        imgBig: "cat12.png",
        postCount: "45",
        url: "",
    },
];

export default categories;
